version: '3.8'
name: qams-backend


services:
  # Base de Datos PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: qams-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      POSTGRES_DB: qams_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qams-network

  # Redis para caché (Mensajería/Background)
  redis:
    image: redis:7-alpine
    container_name: qams-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - qams-network

  # QAMS API Backend
  api:
    build:
      context: c:/diplomado/QAMS
      dockerfile: Dockerfile
    container_name: qams-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=qams_db;Username=postgres;Password=postgres123"
      JwtSettings__Secret: "TuClaveSecretaSuperSeguraDe64CaracteresMinimoPorFavor!!2025QAMS"
      JwtSettings__Issuer: "QAMS.Api"
      JwtSettings__Audience: "QAMS.Client"
      EncryptionSettings__Key: "12345678901234567890123456789012"
      EncryptionSettings__IV: "1234567890123456"
      Redis__Configuration: "redis:6379"
      FRONTEND_URL: "http://localhost:4200"
      SmtpSettings__Username: ${SMTP_USERNAME}
      SmtpSettings__Password: ${SMTP_PASSWORD}
      SmtpSettings__FromEmail: ${SMTP_USERNAME}
    ports:
      - "5000:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - qams-network
    volumes:
      - ./logs:/app/logs
      - uploads_data:/app/wwwroot/uploads

volumes:
  postgres_data:
  redis_data:
  uploads_data:

networks:
  qams-network:
    name: qams-network
    driver: bridge
