// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using QAMS.Infrastructure.Persistence.Configurations;

#nullable disable

namespace QAMS.Infrastructure.Migrations
{
    [DbContext(typeof(QamsDbContext))]
    [Migration("20260216194943_AddProjectStatusAndPriority")]
    partial class AddProjectStatusAndPriority
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.EvidenceType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("evidence_types", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "IMAGE",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 243, DateTimeKind.Utc).AddTicks(147),
                            IsActive = true,
                            Name = "Imagen",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "VIDEO",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 243, DateTimeKind.Utc).AddTicks(149),
                            IsActive = true,
                            Name = "Video",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "DOCUMENT",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 243, DateTimeKind.Utc).AddTicks(150),
                            IsActive = true,
                            Name = "Documento",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "LOG_FILE",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 243, DateTimeKind.Utc).AddTicks(151),
                            IsActive = true,
                            Name = "Archivo de Log",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.ExecutionStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("execution_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PENDING",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 243, DateTimeKind.Utc).AddTicks(2333),
                            Description = "Ejecución creada pero no iniciada.",
                            IsActive = true,
                            Name = "Pendiente",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "IN_PROGRESS",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 243, DateTimeKind.Utc).AddTicks(2335),
                            Description = "Ejecución en curso.",
                            IsActive = true,
                            Name = "En Progreso",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "PASSED",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 243, DateTimeKind.Utc).AddTicks(2336),
                            Description = "Todos los pasos exitosos.",
                            IsActive = true,
                            Name = "Aprobado",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "FAILED",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 243, DateTimeKind.Utc).AddTicks(2337),
                            Description = "Al menos un paso falló.",
                            IsActive = true,
                            Name = "Fallido",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Code = "BLOCKED",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 243, DateTimeKind.Utc).AddTicks(2339),
                            Description = "Impedimento externo.",
                            IsActive = true,
                            Name = "Bloqueado",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Code = "SKIPPED",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 243, DateTimeKind.Utc).AddTicks(2340),
                            Description = "Omitido intencionalmente.",
                            IsActive = true,
                            Name = "Omitido",
                            SortOrder = 6
                        });
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.ProjectStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("project_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PENDIENTE",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 242, DateTimeKind.Utc).AddTicks(7338),
                            Description = "Proyecto registrado pero no iniciado",
                            IsActive = true,
                            Name = "Pendiente",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "EN_PROCESO",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 242, DateTimeKind.Utc).AddTicks(7340),
                            Description = "Proyecto en ejecución activa",
                            IsActive = true,
                            Name = "En Proceso",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "DETENIDO",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 242, DateTimeKind.Utc).AddTicks(7342),
                            Description = "Proyecto pausado o cancelado temporalmente",
                            IsActive = true,
                            Name = "Detenido",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "CERTIFICADO",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 242, DateTimeKind.Utc).AddTicks(7343),
                            Description = "Proyecto completado y validado",
                            IsActive = true,
                            Name = "Certificado",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.StepResultStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("step_result_statuses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "NOT_EXECUTED",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 245, DateTimeKind.Utc).AddTicks(3375),
                            IsActive = true,
                            Name = "No Ejecutado",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "PASSED",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 245, DateTimeKind.Utc).AddTicks(3377),
                            IsActive = true,
                            Name = "Aprobado",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "FAILED",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 245, DateTimeKind.Utc).AddTicks(3378),
                            IsActive = true,
                            Name = "Fallido",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "BLOCKED",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 245, DateTimeKind.Utc).AddTicks(3379),
                            IsActive = true,
                            Name = "Bloqueado",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.TaskPriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("task_priorities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "LOW",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 254, DateTimeKind.Utc).AddTicks(4758),
                            IsActive = true,
                            Name = "Baja",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "MEDIUM",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 254, DateTimeKind.Utc).AddTicks(4771),
                            IsActive = true,
                            Name = "Media",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "HIGH",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 254, DateTimeKind.Utc).AddTicks(4772),
                            IsActive = true,
                            Name = "Alta",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "CRITICAL",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 254, DateTimeKind.Utc).AddTicks(4773),
                            IsActive = true,
                            Name = "Crítica",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.TestCasePriority", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("test_case_priorities", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "LOW",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 255, DateTimeKind.Utc).AddTicks(296),
                            IsActive = true,
                            Name = "Baja",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Code = "MEDIUM",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 255, DateTimeKind.Utc).AddTicks(298),
                            IsActive = true,
                            Name = "Media",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Code = "HIGH",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 255, DateTimeKind.Utc).AddTicks(299),
                            IsActive = true,
                            Name = "Alta",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Code = "CRITICAL",
                            CreatedAt = new DateTime(2026, 2, 16, 19, 49, 43, 255, DateTimeKind.Utc).AddTicks(300),
                            IsActive = true,
                            Name = "Crítica",
                            SortOrder = 4
                        });
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Evidence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<int>("FileTypeId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestExecutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("FileTypeId");

                    b.HasIndex("TestExecutionId");

                    b.ToTable("Evidences");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.ExecutionStepResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActualResult")
                        .HasColumnType("text");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestExecutionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TestStepId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TestExecutionId");

                    b.HasIndex("TestStepId");

                    b.ToTable("ExecutionStepResults");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.KanbanBoard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("KanbanBoards");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.KanbanColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KanbanBoardId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("KanbanBoardId");

                    b.ToTable("KanbanColumns");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.KanbanTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssigneeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KanbanColumnId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TestCaseId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeId");

                    b.HasIndex("KanbanColumnId");

                    b.HasIndex("PriorityId");

                    b.HasIndex("TestCaseId");

                    b.ToTable("KanbanTasks");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("module");

                    b.HasKey("Id");

                    b.ToTable("permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("52455355-5f53-4956-4557-000000000000"),
                            Code = "USERS_VIEW",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ver usuarios",
                            Module = "Users"
                        },
                        new
                        {
                            Id = new Guid("52455355-5f53-5243-4541-544500000000"),
                            Code = "USERS_CREATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crear usuarios",
                            Module = "Users"
                        },
                        new
                        {
                            Id = new Guid("52455355-5f53-5055-4441-544500000000"),
                            Code = "USERS_UPDATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Actualizar usuarios",
                            Module = "Users"
                        },
                        new
                        {
                            Id = new Guid("52455355-5f53-4544-4c45-544500000000"),
                            Code = "USERS_DELETE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eliminar usuarios",
                            Module = "Users"
                        },
                        new
                        {
                            Id = new Guid("52455355-5f53-5341-5349-474e5f524f4c"),
                            Code = "USERS_ASSIGN_ROLES",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Asignar roles a usuarios",
                            Module = "Users"
                        },
                        new
                        {
                            Id = new Guid("454c4f52-5f53-4956-4557-000000000000"),
                            Code = "ROLES_VIEW",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ver roles",
                            Module = "Roles"
                        },
                        new
                        {
                            Id = new Guid("454c4f52-5f53-5243-4541-544500000000"),
                            Code = "ROLES_CREATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crear roles",
                            Module = "Roles"
                        },
                        new
                        {
                            Id = new Guid("454c4f52-5f53-5055-4441-544500000000"),
                            Code = "ROLES_UPDATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Actualizar roles",
                            Module = "Roles"
                        },
                        new
                        {
                            Id = new Guid("454c4f52-5f53-4544-4c45-544500000000"),
                            Code = "ROLES_DELETE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eliminar roles",
                            Module = "Roles"
                        },
                        new
                        {
                            Id = new Guid("454c4f52-5f53-5341-5349-474e5f504552"),
                            Code = "ROLES_ASSIGN_PERMISSIONS",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Asignar permisos a roles",
                            Module = "Roles"
                        },
                        new
                        {
                            Id = new Guid("41544143-4f4c-5347-5f56-494557000000"),
                            Code = "CATALOGS_VIEW",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ver catálogos",
                            Module = "Catalogs"
                        },
                        new
                        {
                            Id = new Guid("41544143-4f4c-5347-5f4d-414e41474500"),
                            Code = "CATALOGS_MANAGE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Administrar catálogos",
                            Module = "Catalogs"
                        },
                        new
                        {
                            Id = new Guid("4a4f5250-4345-5354-5f56-494557000000"),
                            Code = "PROJECTS_VIEW",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ver proyectos",
                            Module = "Projects"
                        },
                        new
                        {
                            Id = new Guid("4a4f5250-4345-5354-5f43-524541544500"),
                            Code = "PROJECTS_CREATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crear proyectos",
                            Module = "Projects"
                        },
                        new
                        {
                            Id = new Guid("4a4f5250-4345-5354-5f55-504441544500"),
                            Code = "PROJECTS_UPDATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Actualizar proyectos",
                            Module = "Projects"
                        },
                        new
                        {
                            Id = new Guid("4a4f5250-4345-5354-5f44-454c45544500"),
                            Code = "PROJECTS_DELETE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eliminar proyectos",
                            Module = "Projects"
                        },
                        new
                        {
                            Id = new Guid("54534554-435f-5341-4553-5f5649455700"),
                            Code = "TEST_CASES_VIEW",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ver casos de prueba",
                            Module = "TestCases"
                        },
                        new
                        {
                            Id = new Guid("54534554-435f-5341-4553-5f4352454154"),
                            Code = "TEST_CASES_CREATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crear casos de prueba",
                            Module = "TestCases"
                        },
                        new
                        {
                            Id = new Guid("54534554-435f-5341-4553-5f5550444154"),
                            Code = "TEST_CASES_UPDATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Actualizar casos de prueba",
                            Module = "TestCases"
                        },
                        new
                        {
                            Id = new Guid("54534554-435f-5341-4553-5f44454c4554"),
                            Code = "TEST_CASES_DELETE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eliminar casos de prueba",
                            Module = "TestCases"
                        },
                        new
                        {
                            Id = new Guid("43455845-5455-4f49-4e53-5f5649455700"),
                            Code = "EXECUTIONS_VIEW",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ver ejecuciones",
                            Module = "Executions"
                        },
                        new
                        {
                            Id = new Guid("43455845-5455-4f49-4e53-5f4352454154"),
                            Code = "EXECUTIONS_CREATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crear ejecuciones",
                            Module = "Executions"
                        },
                        new
                        {
                            Id = new Guid("43455845-5455-4f49-4e53-5f5550444154"),
                            Code = "EXECUTIONS_UPDATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Actualizar ejecuciones",
                            Module = "Executions"
                        },
                        new
                        {
                            Id = new Guid("43455845-5455-4f49-4e53-5f55504c4f41"),
                            Code = "EXECUTIONS_UPLOAD_EVIDENCE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Subir evidencia",
                            Module = "Executions"
                        },
                        new
                        {
                            Id = new Guid("424e414b-4e41-565f-4945-570000000000"),
                            Code = "KANBAN_VIEW",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ver tableros Kanban",
                            Module = "Kanban"
                        },
                        new
                        {
                            Id = new Guid("424e414b-4e41-435f-5245-415445000000"),
                            Code = "KANBAN_CREATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Crear tableros/tareas",
                            Module = "Kanban"
                        },
                        new
                        {
                            Id = new Guid("424e414b-4e41-555f-5044-415445000000"),
                            Code = "KANBAN_UPDATE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Mover tareas",
                            Module = "Kanban"
                        },
                        new
                        {
                            Id = new Guid("424e414b-4e41-445f-454c-455445000000"),
                            Code = "KANBAN_DELETE",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Eliminar tareas",
                            Module = "Kanban"
                        },
                        new
                        {
                            Id = new Guid("48534144-4f42-5241-445f-564945570000"),
                            Code = "DASHBOARD_VIEW",
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ver dashboard",
                            Module = "Dashboard"
                        });
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_user_id");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("priority");

                    b.Property<int>("ProjectStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("project_status_id");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ProjectStatusId");

                    b.ToTable("projects", (string)null);
                });

            modelBuilder.Entity("QAMS.Domain.Entities.ProjectTester", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("project_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTime>("AssignedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("ProjectId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("project_testers", (string)null);
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Acceso total al sistema",
                            IsActive = true,
                            Name = "Administrator"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Ejecución y gestión de pruebas",
                            IsActive = true,
                            Name = "Tester"
                        });
                });

            modelBuilder.Entity("QAMS.Domain.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("role_permissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("52455355-5f53-4956-4557-000000000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("52455355-5f53-5243-4541-544500000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("52455355-5f53-5055-4441-544500000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("52455355-5f53-4544-4c45-544500000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("52455355-5f53-5341-5349-474e5f524f4c"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("454c4f52-5f53-4956-4557-000000000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("454c4f52-5f53-5243-4541-544500000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("454c4f52-5f53-5055-4441-544500000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("454c4f52-5f53-4544-4c45-544500000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("454c4f52-5f53-5341-5349-474e5f504552"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("41544143-4f4c-5347-5f56-494557000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("41544143-4f4c-5347-5f4d-414e41474500"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("4a4f5250-4345-5354-5f56-494557000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("4a4f5250-4345-5354-5f43-524541544500"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("4a4f5250-4345-5354-5f55-504441544500"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("4a4f5250-4345-5354-5f44-454c45544500"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("54534554-435f-5341-4553-5f5649455700"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("54534554-435f-5341-4553-5f4352454154"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("54534554-435f-5341-4553-5f5550444154"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("54534554-435f-5341-4553-5f44454c4554"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("43455845-5455-4f49-4e53-5f5649455700"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("43455845-5455-4f49-4e53-5f4352454154"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("43455845-5455-4f49-4e53-5f5550444154"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("43455845-5455-4f49-4e53-5f55504c4f41"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("424e414b-4e41-565f-4945-570000000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("424e414b-4e41-435f-5245-415445000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("424e414b-4e41-555f-5044-415445000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("424e414b-4e41-445f-454c-455445000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            PermissionId = new Guid("48534144-4f42-5241-445f-564945570000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("4a4f5250-4345-5354-5f56-494557000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("54534554-435f-5341-4553-5f5649455700"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("43455845-5455-4f49-4e53-5f5649455700"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("43455845-5455-4f49-4e53-5f4352454154"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("43455845-5455-4f49-4e53-5f5550444154"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("43455845-5455-4f49-4e53-5f55504c4f41"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("424e414b-4e41-565f-4945-570000000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("424e414b-4e41-555f-5044-415445000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("48534144-4f42-5241-445f-564945570000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            RoleId = new Guid("22222222-2222-2222-2222-222222222222"),
                            PermissionId = new Guid("41544143-4f4c-5347-5f56-494557000000"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestCase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Preconditions")
                        .HasColumnType("text");

                    b.Property<int>("PriorityId")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestSuiteId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PriorityId");

                    b.HasIndex("TestSuiteId");

                    b.ToTable("TestCases");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("ExecutionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("execution_date")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<int>("StatusId")
                        .HasColumnType("integer")
                        .HasColumnName("status_id");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid")
                        .HasColumnName("test_case_id");

                    b.Property<Guid>("TesterId")
                        .HasColumnType("uuid")
                        .HasColumnName("tester_id");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TestCaseId");

                    b.HasIndex("TesterId");

                    b.ToTable("test_executions", (string)null);
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestStep", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedResult")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StepOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TestCaseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TestCaseId");

                    b.ToTable("TestSteps");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestSuite", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TestSuites");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("username");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@qams.local",
                            FullName = "Administrador Base",
                            IsActive = true,
                            PasswordHash = "$2a$12$0jdJPZWmFkqBX5PmpGsjaeXoZqGvvD1fUOifS6Foj9guzZVPZzo.C",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("QAMS.Domain.Entities.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("99999999-9999-9999-9999-999999999999"),
                            RoleId = new Guid("11111111-1111-1111-1111-111111111111"),
                            AssignedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Evidence", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.Catalogs.EvidenceType", "FileType")
                        .WithMany("Evidences")
                        .HasForeignKey("FileTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAMS.Domain.Entities.TestExecution", "TestExecution")
                        .WithMany("Evidences")
                        .HasForeignKey("TestExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileType");

                    b.Navigation("TestExecution");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.ExecutionStepResult", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.Catalogs.StepResultStatus", "Status")
                        .WithMany("ExecutionStepResults")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAMS.Domain.Entities.TestExecution", "TestExecution")
                        .WithMany("StepResults")
                        .HasForeignKey("TestExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAMS.Domain.Entities.TestStep", "TestStep")
                        .WithMany("StepResults")
                        .HasForeignKey("TestStepId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("TestExecution");

                    b.Navigation("TestStep");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.KanbanBoard", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.Project", "Project")
                        .WithMany("KanbanBoards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.KanbanColumn", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.KanbanBoard", "KanbanBoard")
                        .WithMany("Columns")
                        .HasForeignKey("KanbanBoardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KanbanBoard");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.KanbanTask", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.User", "Assignee")
                        .WithMany("AssignedTasks")
                        .HasForeignKey("AssigneeId");

                    b.HasOne("QAMS.Domain.Entities.KanbanColumn", "KanbanColumn")
                        .WithMany("Tasks")
                        .HasForeignKey("KanbanColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAMS.Domain.Entities.Catalogs.TaskPriority", "Priority")
                        .WithMany("KanbanTasks")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAMS.Domain.Entities.TestCase", "TestCase")
                        .WithMany()
                        .HasForeignKey("TestCaseId");

                    b.Navigation("Assignee");

                    b.Navigation("KanbanColumn");

                    b.Navigation("Priority");

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Project", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.User", "CreatedBy")
                        .WithMany("CreatedProjects")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("QAMS.Domain.Entities.Catalogs.ProjectStatus", "ProjectStatus")
                        .WithMany("Projects")
                        .HasForeignKey("ProjectStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");

                    b.Navigation("ProjectStatus");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.ProjectTester", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.Project", "Project")
                        .WithMany("ProjectTesters")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAMS.Domain.Entities.User", "User")
                        .WithMany("ProjectAssignments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAMS.Domain.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestCase", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.Catalogs.TestCasePriority", "Priority")
                        .WithMany("TestCases")
                        .HasForeignKey("PriorityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAMS.Domain.Entities.TestSuite", "TestSuite")
                        .WithMany("TestCases")
                        .HasForeignKey("TestSuiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Priority");

                    b.Navigation("TestSuite");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestExecution", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.Catalogs.ExecutionStatus", "Status")
                        .WithMany("TestExecutions")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("QAMS.Domain.Entities.TestCase", "TestCase")
                        .WithMany("TestExecutions")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAMS.Domain.Entities.User", "Tester")
                        .WithMany("TestExecutions")
                        .HasForeignKey("TesterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Status");

                    b.Navigation("TestCase");

                    b.Navigation("Tester");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestStep", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.TestCase", "TestCase")
                        .WithMany("TestSteps")
                        .HasForeignKey("TestCaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestCase");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestSuite", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.Project", "Project")
                        .WithMany("TestSuites")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.UserRole", b =>
                {
                    b.HasOne("QAMS.Domain.Entities.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QAMS.Domain.Entities.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.EvidenceType", b =>
                {
                    b.Navigation("Evidences");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.ExecutionStatus", b =>
                {
                    b.Navigation("TestExecutions");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.ProjectStatus", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.StepResultStatus", b =>
                {
                    b.Navigation("ExecutionStepResults");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.TaskPriority", b =>
                {
                    b.Navigation("KanbanTasks");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Catalogs.TestCasePriority", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.KanbanBoard", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.KanbanColumn", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Project", b =>
                {
                    b.Navigation("KanbanBoards");

                    b.Navigation("ProjectTesters");

                    b.Navigation("TestSuites");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestCase", b =>
                {
                    b.Navigation("TestExecutions");

                    b.Navigation("TestSteps");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestExecution", b =>
                {
                    b.Navigation("Evidences");

                    b.Navigation("StepResults");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestStep", b =>
                {
                    b.Navigation("StepResults");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.TestSuite", b =>
                {
                    b.Navigation("TestCases");
                });

            modelBuilder.Entity("QAMS.Domain.Entities.User", b =>
                {
                    b.Navigation("AssignedTasks");

                    b.Navigation("CreatedProjects");

                    b.Navigation("ProjectAssignments");

                    b.Navigation("TestExecutions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
